name: Delete Environment (default settings)

on:
  schedule:
    # Runs at 00:00AM UTC
    - cron: '0 0 * * *'
  delete:
    branches-ignore:
      - main

jobs:
  delete:
    runs-on: ubuntu-latest
    steps:
      - uses: strumwolf/delete-deployment-environment@v2
        with:
          # ⚠️ The provided token needs permission for admin write:org
          token: ${{ secrets.GB_TOKEN }}
          environments: uas-web7
          onlyDeactivateDeployments: true
